name: Build Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Build Android
        uses: AcmeSoftwareLLC/flutter-build@v2
        with:
          flutter-version-file: app/pubspec.yam
          script: flutter build apk --release
          working-directory: app

      - name: Upload APK
        uses: actions/upload-artifact@v7
        with:
          name: android-apk
          path: app/build/app/outputs/flutter-apk/app-release.apk
          retention-days: 14
